#!/usr/bin/env ruby
default_port = 3010

if ENV['RAILS_ENV'] == 'development'
  ARGV << "-p#{default_port}" unless ARGV.to_s.include?("-p")
end

require File.dirname(__FILE__) + '/../config/boot'
require 'commands/server'


#require File.expand_path('../../config/boot',  __FILE__)
#require 'commands/server'
